### ISSUE TITLE
1.20.1paper 

### ISSUE THREAD

**Issue by shundebo** [mc23101/BetterFishing#4]
![image](https://github.com/mc23101/BetterFishing/assets/105134757/981abfe8-0f0e-4c99-bcf3-e66e8b960e02)
怎么办
ababab
是不是版本问题
1.20.1paper

**Comment by shundebo** [comment]
Unexpected exception while parsing console command "bf"
org.bukkit.command.CommandException: Cannot execute command 'bf' in plugin BetterFishing v1.1.0 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1006) ~[paper-1.20.1.jar:git-Paper-100]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchServerCommand(CraftServer.java:969) ~[paper-1.20.1.jar:git-Paper-100]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:501) ~[paper-1.20.1.jar:git-Paper-100]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:448) ~[paper-1.20.1.jar:git-Paper-100]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-100]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-100]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-100]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
